[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
viaIR = true
solc = "0.8.13" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
